import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (

    <div className={styles.container}>
    
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder
         blog, hunting coder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload' ></Script> */}
      

      <main className={styles.main}>

      <div className={styles.imgwrap}>
        {/* <Image className={styles.myImg} src="/home.jpg" alt='coder' width={258} height={177} /> */}
        <img className={styles.myImg} src="/home.jpg" alt='coder' width={258} height={177} />
        </div>


        <div className={styles.title}>
          <h1 className=''>&lt;HuntingCoder/&gt;</h1>
        </div>

        
        <div className={styles.mainblog}>
        <h2 className={styles.h2}>Popular Blogs</h2>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  )
}
