import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (

    <div className={styles.container}>
    <style jsx>
    {`
   h2{
    font-size: 35px;
   }
   h3{
    font-size: 25px;
   }
    `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder
         blog, hunting coder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload' ></Script> */}
      

      <main className={styles.main}>

        <div className={styles.title}>
          <h1 className=''>Hunting Coder</h1>
        </div>

        <div className={styles.imgwrap}>
        <Image className={styles.myImg} src="/home.jpg" alt='coder' width={258} height={177} />
        </div>
        
        <p className={styles.logo}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="">
        <h2 className={styles.blogitem}>Popular Blogs</h2>
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is the language use to design logic for web</p>
          </div>
        </div>
      </main>
    </div>
  )
}
